# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_files/bbScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from core.graph import graph

class Ui_bbScreen(object):
    def setupUi(self, bbScreen):
        bbScreen.setObjectName("bbScreen")
        bbScreen.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(bbScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.filename = QtWidgets.QLineEdit(self.centralwidget)
        self.filename.setGeometry(QtCore.QRect(130, 140, 341, 31))
        self.filename.setObjectName("filename")
        self.browseCsvButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseCsvButton.setGeometry(QtCore.QRect(480, 140, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.browseCsvButton.setFont(font)
        self.browseCsvButton.setStyleSheet("background-color: rgb(24, 53, 76);\n"
"color: rgb(230, 236, 235);")
        self.browseCsvButton.setObjectName("browseCsvButton")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(130, 200, 241, 17))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("color: rgb(24, 53, 75);")
        self.checkBox.setObjectName("checkBox")
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(130, 290, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.submitButton.setFont(font)
        self.submitButton.setStyleSheet("background-color: rgb(24, 53, 76);\n"
"color: rgb(230, 236, 235);")
        self.submitButton.setObjectName("submitButton")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(130, 240, 241, 17))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setStyleSheet("color: rgb(24, 53, 75);")
        self.checkBox_2.setObjectName("checkBox_2")
        self.screenTitle = QtWidgets.QLabel(self.centralwidget)
        self.screenTitle.setGeometry(QtCore.QRect(210, 30, 361, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.screenTitle.setFont(font)
        self.screenTitle.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(24, 53, 75);")
        self.screenTitle.setObjectName("screenTitle")
        bbScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(bbScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        bbScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(bbScreen)
        self.statusbar.setObjectName("statusbar")
        bbScreen.setStatusBar(self.statusbar)

        self.retranslateUi(bbScreen)
        QtCore.QMetaObject.connectSlotsByName(bbScreen)

        self.browseCsvButton.clicked.connect(self.browseClicked)
        self.submitButton.clicked.connect(self.submitClicked)
    def retranslateUi(self, bbScreen):
        _translate = QtCore.QCoreApplication.translate
        bbScreen.setWindowTitle(_translate("bbScreen", "MainWindow"))
        self.browseCsvButton.setText(_translate("bbScreen", "Browse CSV file"))
        self.checkBox.setText(_translate("bbScreen", "Return on first leaf"))
        self.submitButton.setText(_translate("bbScreen", "Show result"))
        self.checkBox_2.setText(_translate("bbScreen", "Recursive"))
        self.screenTitle.setText(_translate("bbScreen", "Branch and Bound"))


    def browseClicked(self):
        print('browse clicked')
        fname  = QFileDialog.getOpenFileName(None,"Open File","")
        if fname:
                self.filename.setText(str(fname[0]))

    def submitClicked(self):
        print('submit clicked')
        
                
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    bbScreen = QtWidgets.QMainWindow()
    ui = Ui_bbScreen()
    ui.setupUi(bbScreen)
    bbScreen.show()
    sys.exit(app.exec_())
