# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_files/dsatur.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from functools import partial
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from core.heuristics.d_satur import measure_d_satur
from core.graph import graph


class Ui_dsaturScreen(object):
    def setupUi(self, dsaturScreen):
        dsaturScreen.setObjectName("dsaturScreen")
        dsaturScreen.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(dsaturScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.screenTitle = QtWidgets.QLabel(self.centralwidget)
        self.screenTitle.setGeometry(QtCore.QRect(320, 30, 500, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.screenTitle.setFont(font)
        self.screenTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.screenTitle.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" "color: rgb(24, 53, 75);\n" ""
        )
        self.screenTitle.setObjectName("screenTitle")
        self.filename = QtWidgets.QLineEdit(self.centralwidget)
        self.filename.setGeometry(QtCore.QRect(130, 170, 341, 31))
        self.filename.setObjectName("filename")
        self.browseCsvButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseCsvButton.setGeometry(QtCore.QRect(480, 170, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.browseCsvButton.setFont(font)
        self.browseCsvButton.setStyleSheet(
            "background-color: rgb(24, 53, 76);\n" "color: rgb(230, 236, 235);"
        )
        self.browseCsvButton.setObjectName("browseCsvButton")
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(130, 230, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.submitButton.setFont(font)
        self.submitButton.setStyleSheet(
            "background-color: rgb(24, 53, 76);\n" "color: rgb(230, 236, 235);"
        )
        self.submitButton.setObjectName("submitButton")
        self.resultLabel1 = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel1.setGeometry(QtCore.QRect(130, 300, 200, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.resultLabel1.setFont(font)
        self.resultLabel1.setObjectName("resultLabel1")
        self.resultLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel2.setGeometry(QtCore.QRect(130, 360, 200, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.resultLabel2.setFont(font)
        self.resultLabel2.setObjectName("resultLabel2")
        self.result1 = QtWidgets.QLabel(self.centralwidget)
        self.result1.setGeometry(QtCore.QRect(320, 300, 250, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.result1.setFont(font)
        self.result1.setObjectName("result1")
        self.result2 = QtWidgets.QLabel(self.centralwidget)
        self.result2.setGeometry(QtCore.QRect(320, 360, 250, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.result2.setFont(font)
        self.result2.setObjectName("result2")
        self.returnButton = QtWidgets.QPushButton(self.centralwidget)
        self.returnButton.setGeometry(QtCore.QRect(130, 430, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.returnButton.setFont(font)
        self.returnButton.setStyleSheet(
            "background-color: rgb(24, 53, 76);\n" "color: rgb(230, 236, 235);"
        )
        self.returnButton.setObjectName("returnButton")
        self.refrechButton = QtWidgets.QPushButton(self.centralwidget)
        self.refrechButton.setGeometry(QtCore.QRect(480, 430, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.refrechButton.setFont(font)
        self.refrechButton.setStyleSheet(
            "background-color: rgb(24, 53, 76);\n" "color: rgb(230, 236, 235);"
        )
        self.refrechButton.setObjectName("refrechButton")
        dsaturScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(dsaturScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        dsaturScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(dsaturScreen)
        self.statusbar.setObjectName("statusbar")
        dsaturScreen.setStatusBar(self.statusbar)

        self.retranslateUi(dsaturScreen)
        QtCore.QMetaObject.connectSlotsByName(dsaturScreen)
        self.browseCsvButton.clicked.connect(partial(self.browseClicked))
        self.submitButton.clicked.connect(partial(self.submitClicked))
        self.refrechButton.clicked.connect(partial(self.refreshClicked))

    def retranslateUi(self, dsaturScreen):
        _translate = QtCore.QCoreApplication.translate
        dsaturScreen.setWindowTitle(_translate("dsaturScreen", "MainWindow"))
        self.screenTitle.setText(_translate("dsaturScreen", "Dsatur"))
        self.browseCsvButton.setText(_translate("dsaturScreen", "Browse CSV file"))
        self.submitButton.setText(_translate("dsaturScreen", "Show result"))
        self.resultLabel1.setText(_translate("dsaturScreen", "Number Of Colors"))
        self.resultLabel2.setText(_translate("dsaturScreen", "Execution Time"))
        self.result1.setText(_translate("dsaturScreen", "0"))
        self.result2.setText(_translate("dsaturScreen", "0"))
        self.returnButton.setText(_translate("dsaturScreen", "Return"))
        self.refrechButton.setText(_translate("dsaturScreen", "Refresh"))

    def browseClicked(self):
        print("browse clicked")
        fname = QFileDialog.getOpenFileName(None, "Open File", "")
        if fname:
            self.filename.setText(str(fname[0]))

    def submitClicked(self):
        g = graph()
        g.read(self.filename.text())
        result = measure_d_satur(g)
        self.result1.setText(str(result[0]))
        self.result2.setText("{:.9}s".format(result[1]))
        g.visualize_graph()

    def refreshClicked(self):
        self.filename.setText("")
        self.result1.setText("-")
        self.result2.setText("-")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    dsaturScreen = QtWidgets.QMainWindow()
    ui = Ui_dsaturScreen()
    ui.setupUi(dsaturScreen)
    dsaturScreen.show()
    sys.exit(app.exec_())
