# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './screens/ui_files/greywolf.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from functools import partial
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from core.meta_heuristics.grey_wolf_optimizer.grey_wolf_optimizer import GWO
from core.graph import graph


class Ui_greywolfScreen(object):
    def setupUi(self, greywolfScreen, pile):
        greywolfScreen.setObjectName("greywolfScreen")
        greywolfScreen.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(greywolfScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.result1 = QtWidgets.QLabel(self.centralwidget)
        self.result1.setGeometry(QtCore.QRect(340, 360, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.result1.setFont(font)
        self.result1.setObjectName("result1")
        self.result2 = QtWidgets.QLabel(self.centralwidget)
        self.result2.setGeometry(QtCore.QRect(340, 420, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.result2.setFont(font)
        self.result2.setObjectName("result2")
        self.packsizeLabel = QtWidgets.QLabel(self.centralwidget)
        self.packsizeLabel.setGeometry(QtCore.QRect(430, 220, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.packsizeLabel.setFont(font)
        self.packsizeLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.packsizeLabel.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" "color: rgb(24, 53, 75);\n" ""
        )
        self.packsizeLabel.setObjectName("packsizeLabel")
        self.packsizeInput = QtWidgets.QSpinBox(self.centralwidget)
        self.packsizeInput.setGeometry(QtCore.QRect(570, 220, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.packsizeInput.setFont(font)
        self.packsizeInput.setMaximum(50000)
        self.packsizeInput.setObjectName("packsizeInput")
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(140, 290, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.submitButton.setFont(font)
        self.submitButton.setStyleSheet(
            "background-color: rgb(24, 53, 76);\n" "color: rgb(230, 236, 235);"
        )
        self.submitButton.setObjectName("submitButton")
        self.resultLabel1 = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel1.setGeometry(QtCore.QRect(140, 360, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.resultLabel1.setFont(font)
        self.resultLabel1.setObjectName("resultLabel1")
        self.screenTitle = QtWidgets.QLabel(self.centralwidget)
        self.screenTitle.setGeometry(QtCore.QRect(260, 30, 261, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.screenTitle.setFont(font)
        self.screenTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.screenTitle.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" "color: rgb(24, 53, 75);\n" ""
        )
        self.screenTitle.setObjectName("screenTitle")
        self.resultLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel2.setGeometry(QtCore.QRect(140, 420, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.resultLabel2.setFont(font)
        self.resultLabel2.setObjectName("resultLabel2")
        self.filename = QtWidgets.QLineEdit(self.centralwidget)
        self.filename.setGeometry(QtCore.QRect(140, 160, 341, 31))
        self.filename.setText("")
        self.filename.setObjectName("filename")
        self.returnButton = QtWidgets.QPushButton(self.centralwidget)
        self.returnButton.setGeometry(QtCore.QRect(140, 460, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.returnButton.setFont(font)
        self.returnButton.setStyleSheet(
            "background-color: rgb(24, 53, 76);\n" "color: rgb(230, 236, 235);"
        )
        self.returnButton.setObjectName("returnButton")
        self.browseCsvButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseCsvButton.setGeometry(QtCore.QRect(490, 160, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.browseCsvButton.setFont(font)
        self.browseCsvButton.setStyleSheet(
            "background-color: rgb(24, 53, 76);\n" "color: rgb(230, 236, 235);"
        )
        self.browseCsvButton.setObjectName("browseCsvButton")
        self.iteartionsInput = QtWidgets.QSpinBox(self.centralwidget)
        self.iteartionsInput.setGeometry(QtCore.QRect(280, 220, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.iteartionsInput.setFont(font)
        self.iteartionsInput.setMaximum(50000)
        self.iteartionsInput.setObjectName("iteartionsInput")
        self.refrechButton = QtWidgets.QPushButton(self.centralwidget)
        self.refrechButton.setGeometry(QtCore.QRect(490, 460, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.refrechButton.setFont(font)
        self.refrechButton.setStyleSheet(
            "background-color: rgb(24, 53, 76);\n" "color: rgb(230, 236, 235);"
        )
        self.refrechButton.setObjectName("refrechButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 220, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" "color: rgb(24, 53, 75);\n" ""
        )
        self.label_3.setObjectName("label_3")
        greywolfScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(greywolfScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        greywolfScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(greywolfScreen)
        self.statusbar.setObjectName("statusbar")
        greywolfScreen.setStatusBar(self.statusbar)

        self.retranslateUi(greywolfScreen)
        QtCore.QMetaObject.connectSlotsByName(greywolfScreen)
        self.browseCsvButton.clicked.connect(partial(self.browseClicked))
        self.submitButton.clicked.connect(partial(self.submitClicked))
        self.refrechButton.clicked.connect(partial(self.refreshClicked))
        self.returnButton.clicked.connect(
            partial(self.returnClicked, greywolfScreen, pile)
        )
        self.returnButton.clicked.connect(
            partial(self.returnClicked, greywolfScreen, pile)
        )

    def retranslateUi(self, greywolfScreen):
        _translate = QtCore.QCoreApplication.translate
        greywolfScreen.setWindowTitle(_translate("greywolfScreen", "MainWindow"))
        self.result1.setText(_translate("greywolfScreen", "0"))
        self.result2.setText(_translate("greywolfScreen", "0"))
        self.packsizeLabel.setText(_translate("greywolfScreen", "Pack Size"))
        self.submitButton.setText(_translate("greywolfScreen", "Show result"))
        self.resultLabel1.setText(_translate("greywolfScreen", "Number Of Colors"))
        self.screenTitle.setText(_translate("greywolfScreen", "Grey Wolf"))
        self.resultLabel2.setText(_translate("greywolfScreen", "Execution Time"))
        self.returnButton.setText(_translate("greywolfScreen", "Return"))
        self.browseCsvButton.setText(_translate("greywolfScreen", "Browse CSV file"))
        self.refrechButton.setText(_translate("greywolfScreen", "Refresh"))
        self.label_3.setText(_translate("greywolfScreen", "Max iterations"))

    def browseClicked(self):
        print("browse clicked")
        fname = QFileDialog.getOpenFileName(None, "Open File", "")
        if fname:
            self.filename.setText(str(fname[0]))

    def submitClicked(self):
        print("submit clicked")
        g = graph()
        g.read(self.filename.text())
        iterations = self.iteartionsInput.value()
        packsize = self.packsizeInput.value()
        print(iterations)
        print(packsize)

        result = GWO(g, iterations, packsize)
        print("inside screen: ", result)
        self.result1.setText(str(result[0]))
        self.result2.setText("{:.9}s".format(result[1]))

    def refreshClicked(self):
        pass

    def returnClicked(self, screen, pile):
        print("return ")
        ui = pile.pop()
        print(pile)
        ui.setupUi(screen, pile)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    greywolfScreen = QtWidgets.QMainWindow()
    ui = Ui_greywolfScreen()
    ui.setupUi(greywolfScreen)
    greywolfScreen.show()
    sys.exit(app.exec_())
