# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_files/resultDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *


class Ui_resultDialog(object):
    def setupUi(self, resultDialog):
        resultDialog.setObjectName("resultDialog")
        resultDialog.resize(400, 300)
        self.screenTitle_3 = QtWidgets.QLabel(resultDialog)
        self.screenTitle_3.setGeometry(QtCore.QRect(120, 20, 131, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.screenTitle_3.setFont(font)
        self.screenTitle_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.screenTitle_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(24, 53, 75);\n"
"")
        self.screenTitle_3.setObjectName("screenTitle_3")
        self.screenTitle_4 = QtWidgets.QLabel(resultDialog)
        self.screenTitle_4.setGeometry(QtCore.QRect(40, 110, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.screenTitle_4.setFont(font)
        self.screenTitle_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.screenTitle_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(24, 53, 75);\n"
"")
        self.screenTitle_4.setObjectName("screenTitle_4")
        self.screenTitle_5 = QtWidgets.QLabel(resultDialog)
        self.screenTitle_5.setGeometry(QtCore.QRect(40, 160, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.screenTitle_5.setFont(font)
        self.screenTitle_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.screenTitle_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(24, 53, 75);\n"
"")
        self.screenTitle_5.setObjectName("screenTitle_5")
        self.executionTimeValue = QtWidgets.QLabel(resultDialog)
        self.executionTimeValue.setGeometry(QtCore.QRect(200, 110, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.executionTimeValue.setFont(font)
        self.executionTimeValue.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.executionTimeValue.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(24, 53, 75);\n"
"")
        self.executionTimeValue.setObjectName("executionTimeValue")
        self.colorsValue = QtWidgets.QLabel(resultDialog)
        self.colorsValue.setGeometry(QtCore.QRect(200, 160, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.colorsValue.setFont(font)
        self.colorsValue.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.colorsValue.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(24, 53, 75);\n"
"")
        self.colorsValue.setObjectName("colorsValue")

        self.retranslateUi(resultDialog)
        QtCore.QMetaObject.connectSlotsByName(resultDialog)

    def retranslateUi(self, resultDialog):
        _translate = QtCore.QCoreApplication.translate
        resultDialog.setWindowTitle(_translate("resultDialog", "Dialog"))
        self.screenTitle_3.setText(_translate("resultDialog", "Result"))
        self.screenTitle_4.setText(_translate("resultDialog", "Execution time"))
        self.screenTitle_5.setText(_translate("resultDialog", "Number of colors "))
        self.executionTimeValue.setText(_translate("resultDialog", "12.06s"))
        self.colorsValue.setText(_translate("resultDialog", "52"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    resultDialog = QtWidgets.QDialog()
    ui = Ui_resultDialog()
    ui.setupUi(resultDialog)
    resultDialog.show()
    sys.exit(app.exec_())
