# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_files/rlf.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from functools import partial
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from core.heuristics.RLF import measure_rlf
from core.graph import graph


class Ui_rlfScreen(object):
    def setupUi(self, rlfScreen):
        rlfScreen.setObjectName("rlfScreen")
        rlfScreen.resize(800, 605)
        self.centralwidget = QtWidgets.QWidget(rlfScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.screenTitle_2 = QtWidgets.QLabel(self.centralwidget)
        self.screenTitle_2.setGeometry(QtCore.QRect(350, 20, 500, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.screenTitle_2.setFont(font)
        self.screenTitle_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.screenTitle_2.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" "color: rgb(24, 53, 75);\n" ""
        )
        self.screenTitle_2.setObjectName("screenTitle_2")
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(140, 240, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.submitButton.setFont(font)
        self.submitButton.setStyleSheet(
            "background-color: rgb(24, 53, 76);\n" "color: rgb(230, 236, 235);"
        )
        self.submitButton.setObjectName("submitButton")
        self.browseCsvButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseCsvButton.setGeometry(QtCore.QRect(490, 180, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.browseCsvButton.setFont(font)
        self.browseCsvButton.setStyleSheet(
            "background-color: rgb(24, 53, 76);\n" "color: rgb(230, 236, 235);"
        )
        self.browseCsvButton.setObjectName("browseCsvButton")
        self.filename = QtWidgets.QLineEdit(self.centralwidget)
        self.filename.setGeometry(QtCore.QRect(140, 180, 341, 31))
        self.filename.setObjectName("filename")
        self.resultLabel1 = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel1.setGeometry(QtCore.QRect(140, 310, 200, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.resultLabel1.setFont(font)
        self.resultLabel1.setObjectName("resultLabel1")
        self.result2 = QtWidgets.QLabel(self.centralwidget)
        self.result2.setGeometry(QtCore.QRect(340, 370, 250, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.result2.setFont(font)
        self.result2.setObjectName("result2")
        self.resultLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel2.setGeometry(QtCore.QRect(140, 370, 200, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.resultLabel2.setFont(font)
        self.resultLabel2.setObjectName("resultLabel2")
        self.result1 = QtWidgets.QLabel(self.centralwidget)
        self.result1.setGeometry(QtCore.QRect(340, 310, 250, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.result1.setFont(font)
        self.result1.setObjectName("result1")
        self.returnButton = QtWidgets.QPushButton(self.centralwidget)
        self.returnButton.setGeometry(QtCore.QRect(140, 440, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.returnButton.setFont(font)
        self.returnButton.setStyleSheet(
            "background-color: rgb(24, 53, 76);\n" "color: rgb(230, 236, 235);"
        )
        self.returnButton.setObjectName("returnButton")
        self.refrechButton = QtWidgets.QPushButton(self.centralwidget)
        self.refrechButton.setGeometry(QtCore.QRect(490, 440, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.refrechButton.setFont(font)
        self.refrechButton.setStyleSheet(
            "background-color: rgb(24, 53, 76);\n" "color: rgb(230, 236, 235);"
        )
        self.refrechButton.setObjectName("refrechButton")
        rlfScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(rlfScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        rlfScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(rlfScreen)
        self.statusbar.setObjectName("statusbar")
        rlfScreen.setStatusBar(self.statusbar)

        self.retranslateUi(rlfScreen)
        QtCore.QMetaObject.connectSlotsByName(rlfScreen)
        self.browseCsvButton.clicked.connect(partial(self.browseClicked))
        self.submitButton.clicked.connect(partial(self.submitClicked))
        self.refrechButton.clicked.connect(partial(self.refreshClicked))

    def retranslateUi(self, rlfScreen):
        _translate = QtCore.QCoreApplication.translate
        rlfScreen.setWindowTitle(_translate("rlfScreen", "MainWindow"))
        self.screenTitle_2.setText(_translate("rlfScreen", "RLF"))
        self.submitButton.setText(_translate("rlfScreen", "Show result"))
        self.browseCsvButton.setText(_translate("rlfScreen", "Browse CSV file"))
        self.resultLabel1.setText(_translate("rlfScreen", "Number Of Colors"))
        self.result2.setText(_translate("rlfScreen", "0"))
        self.resultLabel2.setText(_translate("rlfScreen", "Execution Time"))
        self.result1.setText(_translate("rlfScreen", "0"))
        self.returnButton.setText(_translate("rlfScreen", "Return"))
        self.refrechButton.setText(_translate("rlfScreen", "Refresh"))

    def browseClicked(self):
        print("browse clicked")
        fname = QFileDialog.getOpenFileName(None, "Open File", "")
        if fname:
            self.filename.setText(str(fname[0]))

    def submitClicked(self):
        print("submit clicked")
        g = graph()
        g.read(self.filename.text())
        result = measure_rlf(g)
        self.result1.setText(str(result[0]))
        self.result2.setText("{:.9}s".format(result[1]))
        g.visualize_graph()

    def refreshClicked(self):
        self.filename.setText("")
        self.result1.setText("-")
        self.result2.setText("-")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    rlfScreen = QtWidgets.QMainWindow()
    ui = Ui_rlfScreen()
    ui.setupUi(rlfScreen)
    rlfScreen.show()
    sys.exit(app.exec_())
