# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_files/rlf.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *


class Ui_rlfScreen(object):
    def setupUi(self, rlfScreen):
        rlfScreen.setObjectName("rlfScreen")
        rlfScreen.resize(800, 605)
        self.centralwidget = QtWidgets.QWidget(rlfScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.screenTitle_2 = QtWidgets.QLabel(self.centralwidget)
        self.screenTitle_2.setGeometry(QtCore.QRect(350, 20, 91, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.screenTitle_2.setFont(font)
        self.screenTitle_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.screenTitle_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(24, 53, 75);\n"
"")
        self.screenTitle_2.setObjectName("screenTitle_2")
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(140, 240, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.submitButton.setFont(font)
        self.submitButton.setStyleSheet("background-color: rgb(24, 53, 76);\n"
"color: rgb(230, 236, 235);")
        self.submitButton.setObjectName("submitButton")
        self.browseCsvButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseCsvButton.setGeometry(QtCore.QRect(490, 180, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.browseCsvButton.setFont(font)
        self.browseCsvButton.setStyleSheet("background-color: rgb(24, 53, 76);\n"
"color: rgb(230, 236, 235);")
        self.browseCsvButton.setObjectName("browseCsvButton")
        self.filename = QtWidgets.QLineEdit(self.centralwidget)
        self.filename.setGeometry(QtCore.QRect(140, 180, 341, 31))
        self.filename.setObjectName("filename")
        rlfScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(rlfScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        rlfScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(rlfScreen)
        self.statusbar.setObjectName("statusbar")
        rlfScreen.setStatusBar(self.statusbar)

        self.retranslateUi(rlfScreen)
        QtCore.QMetaObject.connectSlotsByName(rlfScreen)
        self.browseCsvButton.clicked.connect(self.browseClicked)
        self.submitButton.clicked.connect(self.submitClicked)

    def retranslateUi(self, rlfScreen):
        _translate = QtCore.QCoreApplication.translate
        rlfScreen.setWindowTitle(_translate("rlfScreen", "MainWindow"))
        self.screenTitle_2.setText(_translate("rlfScreen", "RLF"))
        self.submitButton.setText(_translate("rlfScreen", "Show result"))
        self.browseCsvButton.setText(_translate("rlfScreen", "Browse CSV file"))

    def browseClicked(self):
        print('browse clicked')
        fname  = QFileDialog.getOpenFileName(None,"Open File","")
        if fname:
                self.filename.setText(str(fname[0]))

    def submitClicked(self):
        print('submit clicked')
        
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    rlfScreen = QtWidgets.QMainWindow()
    ui = Ui_rlfScreen()
    ui.setupUi(rlfScreen)
    rlfScreen.show()
    sys.exit(app.exec_())
